
import javax.swing.JOptionPane;

public class TempConvert2 extends javax.swing.JFrame {

    double far, cel;

    public TempConvert2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        farbox = new javax.swing.JTextField();
        celbox = new javax.swing.JTextField();
        ftocbtn = new javax.swing.JButton();
        ctofbtn = new javax.swing.JButton();
        outputlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temp Conversion");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Fahrenheit");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Celsius");

        ftocbtn.setText(">>>>");
        ftocbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftocbtnActionPerformed(evt);
            }
        });

        ctofbtn.setText("<<<<");
        ctofbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctofbtnActionPerformed(evt);
            }
        });

        outputlbl.setBackground(new java.awt.Color(0, 0, 0));
        outputlbl.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        outputlbl.setForeground(new java.awt.Color(255, 255, 0));
        outputlbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        outputlbl.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(outputlbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ftocbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(farbox))
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(celbox)
                            .addComponent(ctofbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(farbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftocbtn)
                    .addComponent(ctofbtn))
                .addGap(18, 18, 18)
                .addComponent(outputlbl, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ftocbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftocbtnActionPerformed
        // TODO add your handling code here:
        //read number in from far box
        try {
            far = Double.parseDouble(farbox.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error - must enter a number");
            return; //stop here
        }

        //convert to cel
        cel = (far - 32.0) * 5.0 / 9.0;
        //print answer in celbox
        celbox.setText(String.format("%.2f", cel));
        //display answer formally in lbl
        outputlbl.setText(String.format("%.2f F = %.2f C", far, cel));
    }//GEN-LAST:event_ftocbtnActionPerformed

    private void ctofbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctofbtnActionPerformed
        // TODO add your handling code here:
        //read number from cel box
        try {
            cel = Double.parseDouble(celbox.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error - must enter a number");
            return; //stop here
        }
        //convert to far
        far = (cel * 9.0 / 5.0) + 32.0;
        farbox.setText(String.format("%.2f", far));
        //display answer formally in lbl
        outputlbl.setText(String.format("%.2f C = %.2f F", cel, far));
        
    }//GEN-LAST:event_ctofbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempConvert2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempConvert2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempConvert2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempConvert2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempConvert2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField celbox;
    private javax.swing.JButton ctofbtn;
    private javax.swing.JTextField farbox;
    private javax.swing.JButton ftocbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel outputlbl;
    // End of variables declaration//GEN-END:variables
}
